### ISSUE TITLE
[EPIC] Speedrun Feature

### ISSUE THREAD

**Issue by Antoine2a** [Antoine2a/fallguys-tools#1]
Todo :
- [ ] Find a lib do display video (somehing interesting here : https://www.youtube.com/watch?v=Rq5SEhs9lws)
> - [ ] should works on youtube
>- [ ] should works on twitch (clips)
>- [ ] should works on twitter
>- [ ] should works on tiktok (opt)
>- [ ] should works on streamable (opt)
- [ ] Create the page of Speedrun (where components will be displayed)
- [ ] Create data of speedrun

Priority : **1** (1 higher priority, 10 minor priority)
